#!/bin/bash
clear
echo -------------------------
echo CleanTech - macOS Edition
echo -------------------------

DATE=`date +%Y-%m-%d`

echo Client Details...
read -p "First Name: " firstname
read -p "Last Name: " lastname

echo Testing sudo password
sudo echo Test passed!
echo If you did not see \"Test Passed\", please close the script and change the password from blank before proceeding...
echo

echo Mounting BEAST Network Share...
NetDir="${HOME}/Desktop/BeastMap"
echo $NetDir
cd ${HOME}/Desktop/
if [ ! -d $NetDir ] ; then
	mkdir $NetDir
	mount -t smbfs //techtutors@TechTutors-1/SysInfo $NetDir
	echo Mapped BEAST Network Share to $NetDir
else
	echo $NetDir exists!
	mount -t smbfs //techtutors@TechTutors-1/SysInfo $NetDir
	echo Mapped BEAST Network Share to $NetDir
fi

echo
echo Dumping Pre-clean System Info... This might take a little while...
system_profiler -detaillevel full -xml > "$NetDir/$lastname-$firstname-preclean-$DATE.spx"
echo

echo Turning on Remote Desktop temporarily...
echo
sudo systemsetup -setremotelogin on
dseditgroup com.apple.access_ssh
dseditgroup -o create -q com.apple.access_ssh
sudo dseditgroup -o edit -a admin -t group com.apple.access_ssh
sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent
sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -specifiedUsers
sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -users `whoami` -access -on -privs -all

echo Installing HomeBrew...
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo Installing Teamviewer, Onyx, CoconutBattery, appcleaner
brew cask install onyx coconutbattery teamviewer appcleaner

echo Installing TT Wifi Access...
read -p "Please enter the current TechTutors WiFi Password: " wifipass
networksetup -addpreferredwirelessnetworkatindex en0 TechTutors 0 WPA2 $wifipass

echo Listing current config...
networksetup -getcomputername
networksetup -listallhardwareports


#### Reversal
# sudo systemsetup -setremotelogin off
# sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -configure -access -off
# networksetup -removepreferredwirelessnetwork en0 TechTutors
# networksetup -removepreferredwirelessnetwork en0 TechTutors-Guest
# rm -Rfv "${HOME}/Desktop/BeastMap"
# 